"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { Plus, Search, BookOpen, Clock, Users, MoreVertical, Sparkles, Eye, Edit } from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { AIBuilderModal } from "@/components/course/ai-builder-modal"
import { useRouter } from "next/navigation"

interface Course {
  id: string; title: string; category: string | null; coverColor: string
  isPublished: boolean; duration: number | null; createdAt: string
  _count: { slides: number; enrollments: number }
}

const COVER_COLORS = [
  "bg-indigo-500","bg-violet-500","bg-blue-500","bg-emerald-500",
  "bg-amber-500","bg-rose-500","bg-pink-500","bg-teal-500",
]

export default function CoursesPage() {
  const [courses, setCourses] = useState<Course[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState("")
  const [showAI, setShowAI] = useState(false)
  const [creating, setCreating] = useState(false)
  const router = useRouter()

  const load = async () => {
    try {
      const res = await fetch("/api/admin/analytics")
      if (res.ok) {
        // Use the existing admin analytics data for course list
      }
      const res2 = await fetch("/api/courses/list")
      if (res2.ok) setCourses(await res2.json())
    } finally { setLoading(false) }
  }

  useEffect(() => { load() }, [])

  const filtered = courses.filter(c => !search || c.title.toLowerCase().includes(search.toLowerCase()))

  const handleAIApply = async (result: { slides: { title: string; content: string; slideType: string; order: number }[]; questions: any[] }) => {
    setCreating(true)
    try {
      // Create course
      const courseRes = await fetch("/api/courses", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: "AI Generated Course",
          description: "Generated by AI — edit to customise",
          isPublished: false,
        }),
      })
      if (!courseRes.ok) { alert("Failed to create course"); return }
      const course = await courseRes.json()

      // Add slides
      for (const slide of result.slides) {
        await fetch(`/api/courses/${course.id}/slides`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(slide),
        })
      }

      setShowAI(false)
      await load()
      router.push(`/courses/${course.id}/edit`)
    } finally { setCreating(false) }
  }

  return (
    <div className="p-8">
      {showAI && <AIBuilderModal onClose={() => setShowAI(false)} onApply={handleAIApply} />}

      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Courses</h1>
          <p className="text-gray-500 mt-1">{loading ? "Loading…" : `${courses.length} courses total`}</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => setShowAI(true)} className="gap-2 text-sm border-indigo-200 text-indigo-700 hover:bg-indigo-50">
            <Sparkles className="h-4 w-4" /> AI Builder
          </Button>
          <Link href="/courses/new">
            <Button className="bg-indigo-600 hover:bg-indigo-700 gap-2 text-sm">
              <Plus className="h-4 w-4" /> New Course
            </Button>
          </Link>
        </div>
      </div>

      <div className="flex gap-3 mb-6">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
          <input value={search} onChange={e => setSearch(e.target.value)}
            className="w-full pl-9 pr-4 py-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            placeholder="Search courses..." />
        </div>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-16">
          <div className="w-7 h-7 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin" />
        </div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-16">
          <BookOpen className="h-12 w-12 text-gray-300 mx-auto mb-4" />
          <p className="text-gray-500">{search ? "No courses match your search" : "No courses yet. Create one or use the AI Builder!"}</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {filtered.map(c => (
            <Card key={c.id} className="overflow-hidden border-0 shadow-sm hover:shadow-md transition-shadow">
              <div className={`h-32 ${c.coverColor} flex items-end p-4`}>
                <div>
                  <span className={`text-[10px] font-medium px-2 py-0.5 rounded-full ${c.isPublished ? "bg-white/20 text-white" : "bg-black/20 text-white/80"}`}>
                    {c.isPublished ? "Published" : "Draft"}
                  </span>
                </div>
              </div>
              <CardContent className="p-4">
                <h3 className="font-semibold text-gray-900 truncate">{c.title}</h3>
                {c.category && <p className="text-xs text-gray-400 mt-0.5">{c.category}</p>}
                <div className="flex items-center gap-4 mt-3 text-xs text-gray-500">
                  <span className="flex items-center gap-1"><BookOpen className="h-3.5 w-3.5" /> {c._count?.slides ?? 0} slides</span>
                  <span className="flex items-center gap-1"><Users className="h-3.5 w-3.5" /> {c._count?.enrollments ?? 0}</span>
                  {c.duration && <span className="flex items-center gap-1"><Clock className="h-3.5 w-3.5" /> {c.duration}m</span>}
                </div>
                <div className="flex items-center gap-2 mt-4">
                  <Link href={`/courses/${c.id}/edit`} className="flex-1">
                    <Button variant="outline" size="sm" className="w-full gap-1.5 text-xs"><Edit className="h-3.5 w-3.5" /> Edit</Button>
                  </Link>
                  <Link href={`/learn/${c.id}`}>
                    <Button size="sm" className="gap-1.5 text-xs bg-indigo-600 hover:bg-indigo-700"><Eye className="h-3.5 w-3.5" /> Preview</Button>
                  </Link>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
