"""comments_and_retry

Revision ID: 9acf884483b9
Revises: 7497425df8bc
Create Date: 2026-06-08 11:28:55.927660
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9acf884483b9'
down_revision: Union[str, None] = '7497425df8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_attempt_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_messages', schema=None) as batch_op:
        batch_op.drop_column('next_attempt_at')
        batch_op.drop_column('attempt_count')

    # ### end Alembic commands ###
