"""invitations_and_outbox

Revision ID: feb2000f209a
Revises: 9e33790c5d6e
Create Date: 2026-06-08 10:13:42.879496
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'feb2000f209a'
down_revision: Union[str, None] = '9e33790c5d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
