"""org_cert_branding

Revision ID: 7497425df8bc
Revises: feb2000f209a
Create Date: 2026-06-08 10:53:18.909536
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7497425df8bc'
down_revision: Union[str, None] = 'feb2000f209a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cert_accent_color', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('cert_signature_text', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cert_signature_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cert_footer_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('cert_footer_text')
        batch_op.drop_column('cert_signature_image_url')
        batch_op.drop_column('cert_signature_text')
        batch_op.drop_column('cert_accent_color')

    # ### end Alembic commands ###
